export const WELCOME_SCREEN = 'ChartGain.screenName.loginModule/WELCOME_SCREEN'
export const START_SCRENN = 'ChartGain.screenName.loginModule/START_SCREEN'
export const LOGIN_SCREEN = 'ChartGain.screenName.loginModule/LOGIN_SCREEN'
export const SIGNUP_SCREEN = 'ChartGain.screenName.loginModule/SIGNUP_SCREEN'

export const HOME_SCREEN = 'ChartGain.screenName.mainModule/HOME_SCREEN'
export const SIGNAL_SCREEN = 'ChartGain.screenName.mainModule/SIGNAL_SCREEN'
export const BROKER_SCREEN = 'CharGain.screenName.mainModule/BROKER_SCREEN'
export const SETTING_SCREEN = 'ChartGain.screenName.mainModule/SETTING_SCREEN'
export const FORGOT_SCREEN  = 'ChartGain.screenName.mainModule/FORGOT_SCREEN'

export const ABOUT_SCREEN = 'ChartGain.screenName.mainModule/ABOUT_SCREEN'
export const LANGUAGE_SCREEN = 'ChartGain.screenName.mainModule/LANGUAGE_SCREEN'
export const SUBSCRIPTION_SCREEN = 'ChartGain.screenName.mainModule/SUBSCRIPTION_SCREEN'
export const RISK_SCREEN = 'ChartGain.screenName.mainModule/RISK_SCREEN'
export const PRIVACY_SCREEN = 'ChartGain.screenName.mainModule/PRIVACY_SCREEN'
export const ADD_SIGNAL_SCREEN = 'ChartGain.screenName.mainModule/ADD_SIGNAL_SCREEN'
export const ADD_EVENT_SCREEN = 'ChartGain.screenName.mainModule/ADD_EVENT_SCREEN'
export const CONTACT_US_SCREEN = 'ChartGain.screenName.mainModule/CONTACT_US_SCREEN'
